### ISSUE TITLE
Feature Request - support bookmarklets

### ISSUE THREAD

**Issue by bybor** [nuchi/bookmark-toolbar-shortcut#1]
I tried this extension and it apparently didn't work, but then I realized that every bookmark I tested was a bookmarklet. It worked fine for regular URLs.

I don't know if current FF allows this, but this would be fantastic to be able to invoke some action through a keyboard shortcut.

Thanks a lot!

**Comment by nuchi** [comment]
My extension uses only the WebExtension Bookmarks API, which I believe does not allow the extension to execute bookmarklet javascript. (If it did, that could potentially be a security issue — a malicious extension could claim to only want to create and load bookmarks, but then surprisingly create a bookmarklet and run arbitrary javascript.)

There may be other extensions out there which request access to your data for all websites (a different WebExtension API), which may be able to do something like what you want (see e.g. https://addons.mozilla.org/en-US/firefox/addon/bookmarklets-context-menu/ for a related example), but I do not plan for my extension to request that permission, and therefore it will be unable to do what you want.

Sorry to disappoint, and thanks for writing — I've received interest in this before (by email) so it's good to have a place to definitively put the answer.
